# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20160105_1323'),
        ('course', '0002_auto_20151020_1638'),
    ]

    operations = [
    ]
